FROM tensorflow/tensorflow:latest-gpu

RUN apt update && apt install -y git vim && \
  pip install transformers && \
  pip install accelerate && \
  pip install protobuf

ADD . /app

RUN git clone https://github.com/apache/dubbo-python.git && \
  cd dubbo-python && \
  pip install -r requirements.txt && \
  pip install .

WORKDIR /app

RUN python /app/setup.py

RUN pip uninstall protobuf -y && \
  pip install protobuf

ENTRYPOINT ["python", "/app/server.py"]